BbWebservices/nbproject - switched to NetBeans 6.7.1. All later versions of Netbeans cause "an incomatibility between the WebFault annotation in the webservice-api.jar library that you have and the one in the rt.jar that ships with the JDK/JRE. Both jars contain the annotation javax.xml.ws.WebFault, but the webservice-api.jar (upgraded/added in Netbean 6.8) contains the property/method messageName, whereas the rt.jar version does not have this property/method. (http://forums.netbeans.org/ptopic34324.html). After digging around you'll realised the only option is to download the webservices-api.jar file, plus wack it onto C:\Program Files\Java\jdk1.6.0_18\jre\lib\endorsed directory to resolve it. (http://brightdadson.blogspot.com/2010/03/javalangnosuchmethoderror.html)
I.e., I understand it as if the problem that can be solved only by altering of JDK6 installation on production server, which does not seem acceptable.

NetBeans 6.7.1 builds webservices with JAX-WS 2.1 version.

More topics on the subject: 
http://forums.netbeans.org/viewtopic.php?t=31581
http://forums.netbeans.org/post-84065.html